// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9qxXB6pKz9guybNezgTDPiCnXIBDudMw',
    appId: '1:663493910827:web:f388e3df48778d0fd6656e',
    messagingSenderId: '663493910827',
    projectId: 'gp1-flutter-partyplanner',
    authDomain: 'gp1-flutter-partyplanner.firebaseapp.com',
    storageBucket: 'gp1-flutter-partyplanner.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5oohJTWiUMMl9X-kuaWebqS5PzZxHwWk',
    appId: '1:663493910827:android:19e29d214732dd92d6656e',
    messagingSenderId: '663493910827',
    projectId: 'gp1-flutter-partyplanner',
    storageBucket: 'gp1-flutter-partyplanner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC45l3egLvv5U_zmTrZuOOeSE8jI2BOqYQ',
    appId: '1:663493910827:ios:05754d2092478a17d6656e',
    messagingSenderId: '663493910827',
    projectId: 'gp1-flutter-partyplanner',
    storageBucket: 'gp1-flutter-partyplanner.appspot.com',
    iosBundleId: 'com.example.gp1Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC45l3egLvv5U_zmTrZuOOeSE8jI2BOqYQ',
    appId: '1:663493910827:ios:24b4d105d29e3030d6656e',
    messagingSenderId: '663493910827',
    projectId: 'gp1-flutter-partyplanner',
    storageBucket: 'gp1-flutter-partyplanner.appspot.com',
    iosBundleId: 'com.example.gp1Flutter.RunnerTests',
  );
}
